### ISSUE TITLE
lazybutton metabug

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2877]
Our WebExtension performance workaround for Firefox 55 involves moving UI code (toolbar button, context menu) into bootstrap.js, and only initializing the WebExtension after the initial click.

NB: there may be unexpected blockers not on this checklist

Here's a checklist of _known_ issues:
- [ ] implement l10n in bootstrap.js for button, context menu (PR #2869)
- [ ] create skeleton toolbar button in bootstrap & remove from webext
- [ ] figure out how to send over tab ID on click (or just show overlay in focused tab/window)
- [ ] check screenshots-enabled prefs before creating toolbar button, context menu
- [ ] context menu: restore URL filtering removed from the webextension
- [ ] toolbar button: restore first run button icon if not onboarded (need to move onboarding state into a pref)
- [ ] figure out if context menu needs `accesskey` attribute
- [ ] get a lazybutton review from Mossop or other Gecko expert/superreviewer

**Comment by 6a68** [comment]
Closing this one as well, looks like we aren't going with this approach after all
