### ISSUE TITLE
8.1.0 release tracking bug

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2892]
Note: leaving this bug open until 8.1.0 lands in central

Creating a release bug following my own, perhaps a little process-heavy, [instructions](https://github.com/mozilla-services/screenshots/blob/master/docs/export-to-firefox.md):

- [x] Bump the minor version number in package.json, following our [version numbering conventions](https://github.com/mozilla-services/screenshots/issues/2647)
- [x] Update changelog: `./bin/generate-commit-log --write stable..master`
- [x] Create tag: `git tag MAJOR.MINOR.0`
- [x] Push tag: `git push --tags`
- [x] Merge master to stable: `git checkout stable && git merge master && git push`
- [x] Create a Bugzilla release bug, copying [bug 1362550](https://bugzil.la/1362550)
  - File the bug under the Firefox product / General component until the Screenshots component is ready ([bug 1361870](https://bugzil.la/1361870))
- [x] Export Screenshots to a local copy of Gecko (see 'Using export_mc.py' section in [docs/export-to-firefox.md](docs/export-to-firefox.md) for details)
  - Ensure your commit message follows the [Firefox bug conventions](https://mdn.io/Committing_Rules_and_Responsibilities), for example: "Bug 1362550 - Export Screenshots 6.6.0 to Firefox; r?kmag"
- [x] Push the changes to the Try server
  - Suggested incantation: `./mach try -b o -p linux64,macosx64,win32,win64 -u all -t all --rebuild-talos 5`
- [x] Push the review request to reviewboard using mozreview, also known as [Mozilla VCS tools](https://mozilla-version-control-tools.readthedocs.io/en/latest/)
  - `git mozreview push` will work if you are using git-cinnabar and have mozreview configured
  - To configure mozreview for use with git and git-cinnabar, see [this helpful blog post](https://sny.no/2016/03/geckogit)
  - Note that this step should automatically attach the patch to the Bugzilla bug and request review from the reviewer mentioned in the commit message (should be reflected as an r? flag on the Bugzilla attachment)
- [x] Bump the major version number in package.json, following our [version numbering conventions](https://github.com/mozilla-services/screenshots/issues/2647) (master only, this is to prepare for the next release)
- [x] Open a Github PR with both version number commits and the changelog commit
- [x] Relax! :beers:

**Comment by 6a68** [comment]
This checklist is awesome. Having some guard rails around an unavoidably tedious process definitely helps: for instance, I had forgotten our numbering scheme involved bumping the version in master after cutting a release.
