### ISSUE TITLE
Investigate "ui is not defined"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2983]
In [this Sentry report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/611970/), probably related to #2902:

```
mousedown@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:514:1
addHandlers/</fn<@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:867:18
watchFunction/this.catcher@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/catcher.js:52:16
EventListener.handleEvent*installHandlersOnDocument@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:888:7
display/this.ui</this.element.onload<@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/ui.js:103:13
watchFunction/this.catcher@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/catcher.js:52:16
EventHandlerNonNull*display/this.ui<@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/ui.js:95:33
display@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/ui.js:81:14
display@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/ui.js:323:14
start@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:374:20
setState@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:192:7
exports.activate@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:821:7
this.uicontrol<@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:924:3
@moz-extension://92b99b93-cd16-4545-acd7-cbb2387ae303/selector/uicontrol.js:6:19
```

It's in the `mousedown` event handler in the `crosshairs` state.  This feels like it should have been fixed by #2942, but apparently was not.

**Comment by SoftVision-CosminMuntean** [comment]
I have observed that a "ReferenceError: ui is not defined" error is displayed in browser console if you save multiple shots consecutive on, but I am not sure if this is related or similar with the above error.

Here is a browser console error:
![ui 2](https://user-images.githubusercontent.com/19226534/26939802-26a3d4dc-4c81-11e7-893e-e28b9f156908.png)

**Comment by ianb** [comment]
There's still an open issue, [per this report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/619711/):

```
Error: Error: Undefined ui in mousedown
mousedown@resource://screenshots-addon/selector/uicontrol.js:517:19
addHandlers/</fn<@resource://screenshots-addon/selector/uicontrol.js:884:18
watchFunction/this.catcher@resource://screenshots-addon/catcher.js:54:16
```

Probably the same underlying cleanup issue.

**Comment by ianb** [comment]
Some more reports in the same category, but a little different:

- [ ] [TypeError: this.element is null](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/621240/)
- [ ] [ReferenceError: shooter is not defined](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/615782/)
- [ ] [errorReferenceError: callBackground is not defined](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/620506/)

**Comment by 6a68** [comment]
I think this should be fixed by #3222

**Comment by 6a68** [comment]
It turns out this can still be reproduced in 57+ if the page action is added to the address bar, then the user clicks the page action rapidly

**Comment by 6a68** [comment]
But note that, by default, the Screenshots item is buried in the page action menu, where it can't be rapidly toggled. Maybe this should be a P2?
