### ISSUE TITLE
[FxA] Release checklist

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3469]
We have it pref'd off, and this is a checklist for what we need to do to turn it on.  Examples:

- [ ] Create QA plan
- [ ] Find the UX review, process it
- [ ] Review strings / localize
- [ ] Create onboarding or engagement technique

**Comment by wresuolc** [comment]
@johngruen when should we turn this on?

**Comment by 6a68** [comment]
@johngruen Is FxA one of the things we want to A/B test in Q4?
