### ISSUE TITLE
Create a release checklist for annotation

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3470]
Annotation is in the codebase but pref'd off, we need to create a checklist of what we need to do to turn it on.  Examples:

- [ ] Find the UX review, process the results ([see doc](https://docs.google.com/document/d/1-bMthyI9SrfhVB--5y4mc6B1EpnUjelUnwgOlmEGpbw/edit))
- [ ] Mark shots as being annotated or not for metrics (so we can see if annotated shots are engaged with differently)
- [ ] Ping Mozilla China
- [ ] Localize strings
- [ ] Decide if we want to A/B test its launch
- [ ] User research
- [ ] Give a place for feedback
- [ ] Fix #3669

**Comment by wresuolc** [comment]
@johngruen when should we turn this on?

**Comment by wresuolc** [comment]
Is #1849 a dupe now?

**Comment by SoftVision-CosminMuntean** [comment]
@ianb we should also add issue #3405 in the checklist.
