### ISSUE TITLE
[Metabug] Make Screenshots a regular, non-embedded webextension

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3875]
_last updated 12 Sep 2018_

Metabug to track work needed to remove the bootstrapped wrapper from Screenshots:

### Lifecycle
- [x] Check the disabled pref inside the webextension before loading the UI code (#4811)
  - The addons team did this for us, moving the disabled pref check into the browser (bug 1488971)
- [x] Init the Library menu item from the webextension (#4812)
  - For now, the Library item is initialized via the embedded API. This will eventually be removed when the addons team allows webextensions to register Library items (bug 1483609)

### Preferences handling
- short-term:
  - [x] Use an API experiment to access about:config prefs (#4800)
  - [x] Make sure we need the `history.enabled` check and, if so, check it from the webextension (#4531)
- longer term:
    - [ ] Replace prefs with `storage.managed` equivalents? (#4773)
    - [ ] Expose disable and disable-upload options in the about:preferences page? (#2711)

### Uploads and ESR
- short-term:
  - [x] Use an API experiment to check the update channel (#4802)
- longer term:
  - [ ] Check if platform is ESR from WebExtension (#4772)
    - [ ] this may require upstream work: https://bugzil.la/1386076
  - [ ] Add server version (necessary if ESR is allowed to upload; first step to ensuring older ESR clients can indicate they are submitting an older version of the upload packet) (#4775)
    - Note that, right now, we are sticking with the original policy of not allowing ESR to upload at all

### Build related:
- [x] Remove `jpm` and bootstrap references from Makefile / build tools
  - Ran into a weird error with `jpm` removal, leaving it in there for now (#4873)

## Completed items:
- [x] Remove startup delays (#3160)
- [x] Remove migration code (#3844)
- [x] Check Telemetry state & send Telemetry pings from WebExtension (#3713)
  - [x] requires Telemetry API for WebExtensions (https://bugzil.la/1280234)
- [x] Move Page Action code to WebExtension
  - [x] landed in m-c directly as https://bugzil.la/1466575

The BMO dependencies are also tracked in the BMO bug: https://bugzil.la/1422437

**Comment by 6a68** [comment]
🎉

Landed the webextension PR in #4864. Individual follow-up bugs have been filed for all the stuff marked 'longer-term' in the description. Closing ^_^
